export { PatientBanner } from "./patient-banner";
export type { PatientBannerProps } from "./patient-banner";
export { ClinicalTabs } from "./clinical-tabs";
export type { ClinicalTab, ClinicalTabsProps } from "./clinical-tabs";
export { RibbonToolbar } from "./ribbon-toolbar";
export type { RibbonGroup, RibbonAction, RibbonToolbarProps } from "./ribbon-toolbar";
export { ClinicalTree } from "./clinical-tree";
export type { TreeItem, ClinicalTreeProps } from "./clinical-tree";
export { ConsultationTable } from "./consultation-table";
export type { Consultation, ConsultationEntry, ConsultationTableProps } from "./consultation-table";
